FROM node:lts as builder
WORKDIR /app
COPY package-lock.json .
COPY package.json .
RUN npm i
COPY . . 
RUN npm run build

FROM amazon/aws-cli:2.1.22
WORKDIR /app
COPY --from=builder /app/build .
RUN aws s3 cp --recursive . s3://movies-aggregator-demo/